### PR TITLE
[JENKINS-31202] Show Trend Graphs in Job view for Workflow builds

### PR DESCRIPTION
**Pull request by benjaminfuchs**
https://issues.jenkins-ci.org/browse/JENKINS-31202

Required changes to show trend graphs in workflow job view.

I tried to stick to the workflow compatibility PR changes to preserve backward compatibility.
A compatible test plugin can be found here: https://github.com/benjaminfuchs/warnings-plugin/tree/JENKINS-31202

Feedback welcome ;)

### CODE REVIEW

**Comment by benjaminfuchs** [comment]
@uhafner Hi, this is idling around now for some time. Anything I could do to move this forward?

**Comment by uhafner** [comment]
Sorry about the delay. I'm currently moving to a new house and still have only a limited internet connection (mobile) :-( So no chance to actually test the change. From the code it looks good to me. Can't you just install the new plug-in in your instance while this change has not been merged?

**Comment by benjaminfuchs** [comment]
Hi, no problem. I already got my changes running with: $ mvn hpi:run but when I tried to install the plugins (analysis-core and warnings: https://github.com/benjaminfuchs/warnings-plugin/tree/JENKINS-31202) I get an error when installing warnings.
[error.txt](https://github.com/jenkinsci/analysis-core-plugin/files/437992/error.txt)

Can this be caused, because I changed the pom.xml of the warnings file?

**Comment by benjaminfuchs** [comment]
Okay, I guess I fixed my problem myself. :hatched_chick:
Instead of setting the dependency scope for analysis-core to "system" I made a local mvn install:install:file ... (what seems to be the recommended way). Just committed the change: https://github.com/benjaminfuchs/warnings-plugin/tree/JENKINS-31202

The error is now gone and I will install it on my instance and provide some feedback after some days in the field.

**Comment by benjaminfuchs** [comment]
So far the changes work fine on my instance :+1: 
I created a PR for the warnings-plugin.
Let me now if I can help any further.
Greetings

**Comment by CFenner** [comment]
Hi @benjaminfuchs, any news on this topic? We would like to use trend graphs for static checks in our workflows. Is there any way to assist?

best regards

**Comment by benjaminfuchs** [comment]
Hi @CFenner, I guess the newest comments are here: https://github.com/jenkinsci/warnings-plugin/pull/80
I started to run the acceptance-test-harness and really had problems with the setup. 
I wasn't able to run the "AnalysisSuite" test at once so I started to run the tests one by one ( i.e. CheckStylePluginTest, FindBugsPluginTest, PmdPluginTest, WarningsPluginTest,
TaskScannerPluginTest, AnalysisCollectorPluginTest).
CheckStylePluginTest, FindBugsPluginTest and PmdPluginTest passed but I had some failures in the WarningsPluginTest and didnt had the time to dig into them: 
[plugins.WarningsPluginTest.txt](https://github.com/jenkinsci/analysis-core-plugin/files/509324/plugins.WarningsPluginTest.txt)
Here is my fork of the acceptance-test-harness (just for info):
https://github.com/benjaminfuchs/acceptance-test-harness/commit/2fb8c05c228fb2e66d1dbbf5e23db13a00ed5127
To run the single tests I ran:
`LOCAL_SNAPSHOTS=true JENKINS_VERSION=1.642.3 BROWSER=chrome mvn -Dtest=WarningsPluginTest`

I guess now with some motivation I will try to get some time the next days and dig in there again, but I guess you are free to try to reproduce the errors and see why the changes in the warnings-plugin cause the errors on the old testcases.

**Comment by uhafner** [comment]
So, I finally managed it to set up my dev environment again:-) I checked this PR using the acceptance test harness (ATH), looks good! Next step: check ATH with https://github.com/jenkinsci/warnings-plugin/pull/80

**Pull request merged**
