### PR TITLE
[JEP-200] [JENKINS-49016] Whitelist AbstractMultimap

### PR DESCRIPTION
**Pull request by jglick**
[JENKINS-49016](https://issues.jenkins-ci.org/browse/JENKINS-49016), pending https://github.com/jenkinsci/jenkins/pull/3241#pullrequestreview-89810209.

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Cannot login from phone. But I approve it

**Comment by oleg-nenashev** [comment]
My plan is to land the core-side fix in the next weekly.
It's Friday, so probably there is no need to release it. But it won't hurt anyway

**Comment by uhafner** [comment]
I just want to wait for the pending security releases. Then I will merge and release this PR.

**Comment by oleg-nenashev** [comment]
Jenkins core 2.103 includes the fix on its side, so this PR can be safely closed

**Comment by uhafner** [comment]
Ok.

**Pull request closed without merging**
